### PR TITLE
Update 24hacktoberfest.md

### PR DESCRIPTION
**Pull request by johnny603**

### CODE REVIEW

**Review by Grammaresque — COMMENTED** [review]
Looks good. Thanks for participating, Johnny!

**Review by Grammaresque — DISMISSED** [review]

**Comment by Grammaresque** [comment]
Oh shoot. This needs to be submitted against development. Thank you!

**Review by Grammaresque — APPROVED** [review]

**Comment by Grammaresque** [comment]
@nazunalika as far as I can tell this PR is correct and ready to be merged.

**Comment by nazunalika** [comment]
Merged with `ce17cbf57fd51763483c7d19603a45f981f7780a`

**Pull request closed without merging**
