### PR TITLE
Social-Media-Post

### PR DESCRIPTION
**Pull request by georgioupanayiotis**

### CODE REVIEW

**Comment by Grammaresque** [comment]
Hello. Thanks for your submission! One thing we need to fix first. Can you please revise this to deploy against the development branch rather than main?

**Comment by georgioupanayiotis** [comment]
> Hello. Thanks for your submission! One thing we need to fix first. Can you please revise this to deploy against the development branch rather than main?
> 
> This contributor guide explains how to do it. https://github.com/rocky-linux/wiki.rockylinux.org/blob/main/CONTRIBUTING.md

just did thanks for pointing me out i have also improve it a bit as the branch is development and not develop 🙂
added a screenshot as well for the rest to be easier!

**Comment by Grammaresque** [comment]
Your FB post is amazing, everything I wanted! Thank you so much. We will amplify that from our main account. Also, thanks for improving the other document as well. I've added the hacktoberfest-accepted label to this PR.

As far as adding the image to contributing.md (which is helpful, thank you!), normally for this repo we add images to the following directory: docs/assets/images and then link to them from there. And I suppose that is also a good instruction to add to the contributor file as well. Do you need an example of how to do that?

**Comment by georgioupanayiotis** [comment]
> Your FB post is amazing, everything I wanted! Thank you so much. We will amplify that from our main account. Also, thanks for improving the other document as well. I've added the hacktoberfest-accepted label to this PR.
> 
> As far as adding the image to contributing.md (which is helpful, thank you!), normally for this repo we add images to the following directory: docs/assets/images and then link to them from there. And I suppose that is also a good instruction to add to the contributor file as well. Do you need an example of how to do that?

Thanks for your kind words! I have made the changes and loading the image from assets folder!

**Comment by Grammaresque** [comment]
Yay, thank you!

**Review by Grammaresque — COMMENTED** [review]
- The participant created a [Facebook](https://www.facebook.com/panayiotisgeorgiou.net/posts/pfbid0KdrYwEcgFZgwoQpxMh4wmdNtg3PF6PK3jezynnrmgtyCV5tcvVJecVpPtFKcwVZxl) post as instructed by the issue.
- Participant updated the Hacktoberfest doc with their name and the URL of the post.
- Participant also updated [contributing.md](https://github.com/rocky-linux/wiki.rockylinux.org/blob/main/CONTRIBUTING.md) to make the instructions more clear
- Participant also added a screenshot to the assets directory, and linked to it from the contributing doc.
- the entire PR has been submitted against development-branch.
As far as I can see, this is all correct.

**Review by Grammaresque — APPROVED** [review]

**Review by nazunalika — APPROVED** [review]

**Pull request merged**
