### PR TITLE
Update 8.6 to 9.0

### PR DESCRIPTION
**Pull request by TrevorBenson**

### CODE REVIEW

**Comment by tcooper** [comment]
Per request in the README.md for this repository please rebase your PR against the development branch.

**Comment by TrevorBenson** [comment]
@tcooper Rebased onto development.

**Review by tcooper — DISMISSED** [review]
Thanks for your submission.

**Comment by tcooper** [comment]
Sorry I missed this last time and I know it's a lot of effort for two characters but the main branch of this repo requires all commits be signed.

If you want to have this contribution added please [GPG sign commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) with key added to your profile.

**Comment by TrevorBenson** [comment]
@tcooper Commit is GPG Signed. I've signed all agreements and added my GPG and SSH to the RSA profile.

**Pull request merged**
