### PR TITLE
Update the community page with correct people and names

### PR DESCRIPTION
**Pull request by jonasrosland**
This will update the community page with correct people and names

### CODE REVIEW

**Comment by NeilHanlon** [comment]
Hi Jonas,

Thanks for the contribution! Could you please rebase this against the `development` branch?

--Neil

**Comment by jonasrosland** [comment]
I think `development` and `main` are both in sync right now, so not sure a rebase is needed here.
Would you rather I change the PR towards `development` instead of `main`?

**Comment by NeilHanlon** [comment]
> I think `development` and `main` are both in sync right now, so not sure a rebase is needed here. Would you rather I change the PR towards `development` instead of `main`?

Yep, that's what I meant to say.. the words came out wrong :) 

Thanks!

FYI the Community team asked me to spin up a dedicated wiki for them (at https://community.rocky.page/) -- It's still up for discussion exactly what we'll do with the content here, but I am hoping that we can keep it, but build it from the disparate SIG wikis during release (mkdocs-material has some support for this already)

**Comment by jonasrosland** [comment]
Changed the target base branch :)

**Review by NeilHanlon — APPROVED** [review]

**Pull request merged**
